name: BookManager
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  core_elements: any
  paper_elements: '>=0.4.0 <0.5.0'
transformers:
- polymer:
    entry_points: web/index.html
